<?php

declare(strict_types=1);

namespace Brackets\AdminGenerator\Tests\Feature\Views;

use Brackets\AdminGenerator\Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\File;

class FormTest extends TestCase
{
    use DatabaseMigrations;

    public function testViewFormShouldGetAutoGenerated(): void
    {
        $elementsPath = resource_path('views/admin/category/components/form-elements.blade.php');
        $createPath = resource_path('views/admin/category/create.blade.php');
        $editPath = resource_path('views/admin/category/edit.blade.php');
        $formJsPath = resource_path('js/admin/category/Form.js');
        $indexJsPath = resource_path('js/admin/category/index.js');
        $bootstrapJsPath = resource_path('js/admin/index.js');

        self::assertFileDoesNotExist($elementsPath);
        self::assertFileDoesNotExist($createPath);
        self::assertFileDoesNotExist($editPath);
        self::assertFileDoesNotExist($formJsPath);
        self::assertFileDoesNotExist($indexJsPath);
        self::assertFileDoesNotExist($bootstrapJsPath);


        $this->artisan('admin:generate:form', [
            'table_name' => 'categories',
        ]);

        self::assertFileExists($elementsPath);
        self::assertFileExists($createPath);
        self::assertFileExists($editPath);
        self::assertFileExists($formJsPath);
        self::assertFileExists($indexJsPath);
        self::assertFileExists($bootstrapJsPath);
        self::assertMatchesFileSnapshot($elementsPath);
        self::assertMatchesFileSnapshot($createPath);
        self::assertMatchesFileSnapshot($editPath);
        self::assertMatchesFileSnapshot($formJsPath);
        self::assertMatchesFileSnapshot($indexJsPath);
        self::assertMatchesFileSnapshot($bootstrapJsPath);
        self::assertStringStartsWith('<div ', File::get($elementsPath));
        self::assertStringStartsWith('@extends(\'brackets/admin-ui::admin.layout.default\')', File::get($createPath));
        self::assertStringStartsWith('@extends(\'brackets/admin-ui::admin.layout.default\')', File::get($editPath));
        self::assertStringStartsWith('import AppForm from \'../app-components/Form/AppForm\';

Vue.component(\'category-form\', {
    mixins: [AppForm]', File::get($formJsPath));
        self::assertStringStartsWith('import \'./Form\'', File::get($indexJsPath));
        self::assertStringStartsWith('import \'./category\';', File::get($bootstrapJsPath));
    }

    public function testViewFormShouldGetGeneratedWithCustomModel(): void
    {
        $elementsPath = resource_path('views/admin/billing/my-article/components/form-elements.blade.php');
        $createPath = resource_path('views/admin/billing/my-article/create.blade.php');
        $editPath = resource_path('views/admin/billing/my-article/edit.blade.php');
        $formJsPath = resource_path('js/admin/billing-my-article/Form.js');
        $indexJsPath = resource_path('js/admin/billing-my-article/index.js');
        $bootstrapJsPath = resource_path('js/admin/index.js');

        self::assertFileDoesNotExist($elementsPath);
        self::assertFileDoesNotExist($createPath);
        self::assertFileDoesNotExist($editPath);
        self::assertFileDoesNotExist($formJsPath);
        self::assertFileDoesNotExist($indexJsPath);
        self::assertFileDoesNotExist($bootstrapJsPath);

        $this->artisan('admin:generate:form', [
            'table_name' => 'categories',
            '--model-name' => 'Billing\\MyArticle',
        ]);

        self::assertFileExists($elementsPath);
        self::assertFileExists($createPath);
        self::assertFileExists($editPath);
        self::assertFileExists($formJsPath);
        self::assertFileExists($indexJsPath);
        self::assertFileExists($bootstrapJsPath);
        self::assertMatchesFileSnapshot($elementsPath);
        self::assertMatchesFileSnapshot($createPath);
        self::assertMatchesFileSnapshot($editPath);
        self::assertMatchesFileSnapshot($formJsPath);
        self::assertMatchesFileSnapshot($indexJsPath);
        self::assertMatchesFileSnapshot($bootstrapJsPath);
        self::assertStringStartsWith('<div ', File::get($elementsPath));
        self::assertStringStartsWith('@extends(\'brackets/admin-ui::admin.layout.default\')', File::get($createPath));
        self::assertStringStartsWith('@extends(\'brackets/admin-ui::admin.layout.default\')', File::get($editPath));
        self::assertStringStartsWith('import AppForm from \'../app-components/Form/AppForm\';

Vue.component(\'billing-my-article-form\', {
    mixins: [AppForm]', File::get($formJsPath));
        self::assertStringStartsWith('import \'./Form\'', File::get($indexJsPath));
        self::assertStringStartsWith('import \'./billing-my-article\';', File::get($bootstrapJsPath));
    }
}
