<?php

declare(strict_types=1);

namespace Brackets\AdminGenerator\Tests\Feature\Views;

use Brackets\AdminGenerator\Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\File;

class FullFormTest extends TestCase
{
    use DatabaseMigrations;

    public function testViewFullFormShouldGetAutoGenerated(): void
    {
        $formPath = resource_path('views/admin/category/form.blade.php');
        $formJsPath = resource_path('js/admin/category/Form.js');

        self::assertFileDoesNotExist($formPath);
        self::assertFileDoesNotExist($formJsPath);

        $this->artisan('admin:generate:full-form', [
            'table_name' => 'categories',
        ]);

        self::assertFileExists($formPath);
        self::assertFileExists($formJsPath);
        self::assertMatchesFileSnapshot($formPath);
        self::assertMatchesFileSnapshot($formJsPath);
        self::assertStringStartsWith('@extends(\'brackets/admin-ui::admin.layout.default\')', File::get($formPath));
        self::assertStringStartsWith('import AppForm from \'../app-components/Form/AppForm\';

Vue.component(\'category-form\', {
    mixins: [AppForm]', File::get($formJsPath));
    }

    public function testYouCanPassYourOwnFilePath(): void
    {
        $formPath = resource_path('views/admin/profile/edit-password.blade.php');
        $formJsPath = resource_path('js/admin/profile-edit-password/Form.js');

        self::assertFileDoesNotExist($formPath);
        self::assertFileDoesNotExist($formJsPath);

        $this->artisan('admin:generate:full-form', [
            'table_name' => 'categories',
            '--file-name' => 'profile/edit-password',
        ]);

        self::assertFileExists($formPath);
        self::assertFileExists($formJsPath);
        self::assertMatchesFileSnapshot($formPath);
        self::assertMatchesFileSnapshot($formJsPath);
        self::assertStringStartsWith('@extends(\'brackets/admin-ui::admin.layout.default\')', File::get($formPath));
        self::assertStringContainsString(
            ':action="\'{{ route(\'admin/profile/edit-password\', [\'category\' => $category]) }}\'"',
            File::get($formPath),
        );
        self::assertStringStartsWith('import AppForm from \'../app-components/Form/AppForm\';

Vue.component(\'profile-edit-password-form\', {
    mixins: [AppForm]', File::get($formJsPath));
    }
}
