<?php

declare(strict_types=1);

namespace Brackets\AdminGenerator\Tests\Feature\Views;

use Brackets\AdminGenerator\Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class ViewFullFormTest extends TestCase
{
    use DatabaseMigrations;

    public function testViewFullFormShouldGetAutoGenerated(): void
    {
        $formPath = resource_path('views/admin/category/form.blade.php');
        $formJsPath = resource_path('js/admin/category/Form.js');

        self::assertFileDoesNotExist($formPath);
        self::assertFileDoesNotExist($formJsPath);

        $this->artisan('admin:generate:full-form', [
            'table_name' => 'categories',
        ]);

        self::assertFileExists($formPath);
        self::assertFileExists($formJsPath);
        self::assertMatchesFileSnapshot($formPath);
        self::assertMatchesFileSnapshot($formJsPath);
    }

    public function testYouCanPassYourOwnFilePath(): void
    {
        $formPath = resource_path('views/admin/profile/edit-password.blade.php');
        $formJsPath = resource_path('js/admin/profile-edit-password/Form.js');

        self::assertFileDoesNotExist($formPath);
        self::assertFileDoesNotExist($formJsPath);

        $this->artisan('admin:generate:full-form', [
            'table_name' => 'categories',
            '--file-name' => 'profile/edit-password',
        ]);

        self::assertFileExists($formPath);
        self::assertFileExists($formJsPath);
        self::assertMatchesFileSnapshot($formPath);
        self::assertMatchesFileSnapshot($formJsPath);
    }
}
